# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'data_tool_main.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(689, 710)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 190, 651, 101))
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setInputMethodHints(QtCore.Qt.ImhNone)
        self.groupBox_2.setObjectName("groupBox_2")
        self.comboBox = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox.setGeometry(QtCore.QRect(30, 40, 87, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox_2 = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_2.setGeometry(QtCore.QRect(150, 40, 87, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.comboBox_2.setFont(font)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(20, 300, 651, 181))
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.shear_radio_2 = QtWidgets.QRadioButton(self.groupBox_3)
        self.shear_radio_2.setGeometry(QtCore.QRect(30, 40, 115, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.shear_radio_2.setFont(font)
        self.shear_radio_2.setCheckable(True)
        self.shear_radio_2.setChecked(True)
        self.shear_radio_2.setObjectName("shear_radio_2")
        self.file_radio_2 = QtWidgets.QRadioButton(self.groupBox_3)
        self.file_radio_2.setGeometry(QtCore.QRect(30, 80, 115, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.file_radio_2.setFont(font)
        self.file_radio_2.setObjectName("file_radio_2")
        self.program_radio_2 = QtWidgets.QRadioButton(self.groupBox_3)
        self.program_radio_2.setGeometry(QtCore.QRect(30, 120, 115, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.program_radio_2.setFont(font)
        self.program_radio_2.setObjectName("program_radio_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        self.label_3.setGeometry(QtCore.QRect(300, 80, 72, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        self.label_4.setGeometry(QtCore.QRect(130, 80, 72, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        self.label_5.setGeometry(QtCore.QRect(470, 80, 72, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.file_lineEdit_5 = QtWidgets.QLineEdit(self.groupBox_3)
        self.file_lineEdit_5.setGeometry(QtCore.QRect(200, 80, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.file_lineEdit_5.setFont(font)
        self.file_lineEdit_5.setObjectName("file_lineEdit_5")
        self.file_lineEdit_6 = QtWidgets.QLineEdit(self.groupBox_3)
        self.file_lineEdit_6.setGeometry(QtCore.QRect(370, 80, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.file_lineEdit_6.setFont(font)
        self.file_lineEdit_6.setObjectName("file_lineEdit_6")
        self.file_lineEdit_7 = QtWidgets.QLineEdit(self.groupBox_3)
        self.file_lineEdit_7.setGeometry(QtCore.QRect(540, 80, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.file_lineEdit_7.setFont(font)
        self.file_lineEdit_7.setObjectName("file_lineEdit_7")
        self.file_lineEdit_8 = QtWidgets.QLineEdit(self.groupBox_3)
        self.file_lineEdit_8.setGeometry(QtCore.QRect(370, 120, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.file_lineEdit_8.setFont(font)
        self.file_lineEdit_8.setObjectName("file_lineEdit_8")
        self.file_lineEdit_9 = QtWidgets.QLineEdit(self.groupBox_3)
        self.file_lineEdit_9.setGeometry(QtCore.QRect(200, 120, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.file_lineEdit_9.setFont(font)
        self.file_lineEdit_9.setObjectName("file_lineEdit_9")
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setGeometry(QtCore.QRect(300, 120, 72, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setGeometry(QtCore.QRect(130, 120, 72, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.data_Button = QtWidgets.QPushButton(self.centralwidget)
        self.data_Button.setGeometry(QtCore.QRect(110, 500, 461, 61))
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.data_Button.setFont(font)
        self.data_Button.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.data_Button.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.data_Button.setObjectName("data_Button")
        self.comp_Button = QtWidgets.QPushButton(self.centralwidget)
        self.comp_Button.setGeometry(QtCore.QRect(110, 580, 461, 61))
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.comp_Button.setFont(font)
        self.comp_Button.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.comp_Button.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.comp_Button.setObjectName("comp_Button")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 10, 651, 171))
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.program_comboBox = QtWidgets.QComboBox(self.groupBox)
        self.program_comboBox.setGeometry(QtCore.QRect(130, 120, 151, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(240, 204, 19))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 224, 40))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.program_comboBox.setPalette(palette)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.program_comboBox.setFont(font)
        self.program_comboBox.setObjectName("program_comboBox")
        self.program_radio = QtWidgets.QRadioButton(self.groupBox)
        self.program_radio.setGeometry(QtCore.QRect(30, 120, 115, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.program_radio.setFont(font)
        self.program_radio.setObjectName("program_radio")
        self.file_radio = QtWidgets.QRadioButton(self.groupBox)
        self.file_radio.setGeometry(QtCore.QRect(30, 80, 115, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.file_radio.setFont(font)
        self.file_radio.setObjectName("file_radio")
        self.select_file_button = QtWidgets.QPushButton(self.groupBox)
        self.select_file_button.setGeometry(QtCore.QRect(530, 80, 93, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.select_file_button.setFont(font)
        self.select_file_button.setCheckable(False)
        self.select_file_button.setAutoRepeatDelay(300)
        self.select_file_button.setAutoDefault(True)
        self.select_file_button.setDefault(False)
        self.select_file_button.setFlat(False)
        self.select_file_button.setObjectName("select_file_button")
        self.shear_radio = QtWidgets.QRadioButton(self.groupBox)
        self.shear_radio.setGeometry(QtCore.QRect(30, 40, 115, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.shear_radio.setFont(font)
        self.shear_radio.setCheckable(True)
        self.shear_radio.setChecked(True)
        self.shear_radio.setObjectName("shear_radio")
        self.file_lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.file_lineEdit.setGeometry(QtCore.QRect(130, 80, 371, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.file_lineEdit.setFont(font)
        self.file_lineEdit.setObjectName("file_lineEdit")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(300, 120, 72, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.file_lineEdit_2 = QtWidgets.QLineEdit(self.groupBox)
        self.file_lineEdit_2.setGeometry(QtCore.QRect(370, 120, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.file_lineEdit_2.setFont(font)
        self.file_lineEdit_2.setInputMethodHints(QtCore.Qt.ImhPreferNumbers)
        self.file_lineEdit_2.setClearButtonEnabled(False)
        self.file_lineEdit_2.setObjectName("file_lineEdit_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(470, 120, 72, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.file_lineEdit_3 = QtWidgets.QLineEdit(self.groupBox)
        self.file_lineEdit_3.setGeometry(QtCore.QRect(540, 120, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.file_lineEdit_3.setFont(font)
        self.file_lineEdit_3.setObjectName("file_lineEdit_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 689, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_2 = QtWidgets.QAction(MainWindow)
        self.action_2.setObjectName("action_2")
        self.actionBeyond_Compare = QtWidgets.QAction(MainWindow)
        self.actionBeyond_Compare.setObjectName("actionBeyond_Compare")
        self.action_5 = QtWidgets.QAction(MainWindow)
        self.action_5.setObjectName("action_5")
        self.menu.addAction(self.action_2)
        self.menu.addAction(self.actionBeyond_Compare)
        self.menu_2.addAction(self.action_5)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.label_3.setBuddy(self.file_lineEdit_6)
        self.label_4.setBuddy(self.file_lineEdit_5)
        self.label_5.setBuddy(self.file_lineEdit_7)
        self.label_6.setBuddy(self.file_lineEdit_8)
        self.label_7.setBuddy(self.file_lineEdit_9)
        self.label.setBuddy(self.file_lineEdit_2)
        self.label_2.setBuddy(self.file_lineEdit_3)

        self.retranslateUi(MainWindow)
        self.comboBox.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_2.setTitle(_translate("MainWindow", "2.规格设置"))
        self.comboBox.setCurrentText(_translate("MainWindow", "4字节"))
        self.comboBox.setItemText(0, _translate("MainWindow", "1字节"))
        self.comboBox.setItemText(1, _translate("MainWindow", "2字节"))
        self.comboBox.setItemText(2, _translate("MainWindow", "4字节"))
        self.comboBox.setItemText(3, _translate("MainWindow", "8字节"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "大写字母"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "小写字母"))
        self.groupBox_3.setTitle(_translate("MainWindow", "3.数据重整设置"))
        self.shear_radio_2.setText(_translate("MainWindow", "无"))
        self.file_radio_2.setText(_translate("MainWindow", "抽取"))
        self.program_radio_2.setText(_translate("MainWindow", "重排"))
        self.label_3.setText(_translate("MainWindow", "有效长度"))
        self.label_4.setText(_translate("MainWindow", "分段长度"))
        self.label_5.setText(_translate("MainWindow", "段内偏移"))
        self.label_6.setText(_translate("MainWindow", "子段长度"))
        self.label_7.setText(_translate("MainWindow", "母段长度"))
        self.data_Button.setText(_translate("MainWindow", "4.数据生成"))
        self.comp_Button.setText(_translate("MainWindow", "5.选择比对文件"))
        self.groupBox.setTitle(_translate("MainWindow", "1.数据源选择"))
        self.program_radio.setText(_translate("MainWindow", "程序"))
        self.file_radio.setToolTip(_translate("MainWindow", "可输入多个文件，用\";\"隔开"))
        self.file_radio.setText(_translate("MainWindow", "文件"))
        self.select_file_button.setText(_translate("MainWindow", "选择文件"))
        self.shear_radio.setText(_translate("MainWindow", "剪切板"))
        self.label.setText(_translate("MainWindow", "内存地址"))
        self.label_2.setText(_translate("MainWindow", "数组长度"))
        self.menu.setTitle(_translate("MainWindow", "配置"))
        self.menu_2.setTitle(_translate("MainWindow", "帮助"))
        self.action_2.setText(_translate("MainWindow", "输出文件路径"))
        self.actionBeyond_Compare.setText(_translate("MainWindow", "Beyond Compare路径"))
        self.action_5.setText(_translate("MainWindow", "关于"))

